

function trOptions = set_training_options(pram,XVal,YVal)

  trOptions = trainingOptions('sgdm', ...
                              'Momentum',0.9, ...
                              'InitialLearnRate',pram.initLearningRate, ...
                              'MiniBatchSize',pram.miniBatchSize,...
                              'LearnRateSchedule','piecewise', ...
                              'LearnRateDropPeriod',pram.dropPeriod, ...
                              'LearnRateDropFactor',pram.learningRateFactor, ...
                              'L2Regularization',pram.l2reg, ...
                              'MaxEpochs',pram.maxEpochs ,...                        
                              'GradientThresholdMethod','l2norm', ...
                              'Plots','training-progress', ...
                              'GradientThreshold',0.01,...
                              'ExecutionEnvironment',pram.excEnv,...
                              'ValidationData',{XVal,YVal});

end